### PR TITLE
fix: images not showing

### PR DESCRIPTION
**Pull request by brijesh-rohilla**
On last update:- 
relative path of images did not locate the assets folder.

**Before** my changes:- 
image

**After** my changes:- 
image

### CODE REVIEW

**Comment by alok722** [comment]
Thanks for bringing this to my notice. But I will have to close this PR as it requires few additional changes likes:
- changes should not be done in `dist/lectures.html` and `notes/lectures.md`. HTML and PDF are generated using the `npm run build` command.
- Also in all the notes files, locally absolute path doesn't work. So all the image paths need to be updated with relative paths. Example is attached below.

## Using Absolute path in local

Screenshot 2023-12-28 114954

## Using Relative path in local

Screenshot 2023-12-28 115009

**Comment by alok722** [comment]
@brijesh-rohilla I have pushed the changes, could you please re-verify and highlight if I have missed anything..

**Comment by brijesh-rohilla** [comment]
I just missed my chance to become a contributor to my **favorite GitHub repository**😢
@alok722 bhai please don't make changes from your side directly.

Its hearts💔

**Comment by brijesh-rohilla** [comment]
I just missed my chance to become a contributor to my favorite GitHub repository😢
@alok722 bhai please don't make changes from your side directly.

It hurts💔

**Pull request closed without merging**
