### PR TITLE
Episode1

### PR DESCRIPTION
**Pull request by Dinesh9350**
repeated line number 1 of episode 1 is removed.

### CODE REVIEW

**Comment by Dinesh9350** [comment]
removed repeated line

**Comment by alok722** [comment]
Please check the contribution guidelines in README file, commit your change using `npm run commit` script so that pdf and webpage will be updated accordingly.

**Comment by alok722** [comment]
I am closing the PR as it is open for few days and you haven't responded to my latest comment. I am doing the change myself, thank you for noticing. Next time you plan to improve the repo please abide by the contributing guidelines as this repo also contains PDFs and webpage which get compiled and build when you run `npm run commit`. for more details, please checkout the *package.json* file.

**Comment by Dinesh9350** [comment]
It's fine brother, Thank you so much for providing the notes. I'll mail you if I found any error or something. kindly drop your Gmail.

**Comment by alok722** [comment]
> It's fine brother, Thank you so much for providing the notes. I'll mail you if I found any error or something. kindly drop your Gmail.

You don't need to email, you can submit the PR, but the way you will commit your file before pushing will be different.
Suppose you forked and then cloned the repo in your local. After making necessary change you simply do `git add .` and then `git commit -m "commit message` but instead over here you are suppose to run `npm run commit` and it will take care of updating pdf file, updating webpage, staging and also the commit. This step is required so that your changes are reflected in pdf and web version.

Hope you understand

**Pull request closed without merging**
